<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuDishTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>1,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>2,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>3,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>4,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>5,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>6,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>7,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>8,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>9,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>10,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>11,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>1,
            'id_dish'=>12,
            'relacion'=>"",
        ]);

        //MENU2
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>1,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>3,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>4,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>13,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>5,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>14,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>7,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>15,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>16,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>9,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>11,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>2,
            'id_dish'=>12,
            'relacion'=>"",
        ]);

        //Menu3

        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>1,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>2,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>3,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>4,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>17,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>5,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>7,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>18,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>15,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>9,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>13,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>16,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>11,
            'relacion'=>"",
        ]);
        DB::table('menu_dish')->insert([
            'id_menu'=>3,
            'id_dish'=>12,
            'relacion'=>"",
        ]);

    }
}
